#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#src
cd src
wclean libso dynamicFvMesh
wclean libso combustionModels
wclean libso thermophysicalModels/radiationModels
cd ..

#solvers
cd applications/solvers/combustion
wclean diffusionFireFoam
cd ../../..
