#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#src
cd src
wmake libso dynamicFvMesh
wmake libso combustionModels
wmake libso thermophysicalModels/radiationModels
wmake libso finiteVolume/fields/fvPatchFields/custom/
wmake libso regionModels/regionModel
wmake libso regionModels/pyrolysisModels
wmake libso regionModels/surfaceFilmModels
wmake libso regionModels/regionCoupling
wmake libso lagrangian/intermediate
wmake libso lagrangian/turbulence
cd ..

#solvers
cd applications/solvers/combustion
wmake diffusionFireFoam
cd ../../..
