#!/bin/bash

rm -rf 0

rm constant/polyMesh/

rm -rf runFiles

rm log.*

rm -rf 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9*

rm -rf processor*

rm -rf dynamicCode

rm -rf postProcessing

#------------------------------------------------------------------------------
