#!/bin/sh

cp -rf 0_backup 0

echo "building mesh"
blockMesh > log.blockMesh

topoSet -dict system/topoSetDict1 > log.topoSet1
createPatch -dict system/createPatchDict -overwrite > log.createPatch

mkdir runFiles
mv log* runFiles

echo "running solver"
diffusionFireFoam > log.diffusionFireFoam

#------------------------------------------------------------------------------
