#!/bin/bash

mkdir runFiles

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=fireDyMFoam

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication -s f \
	    topoSet -dict system/f.topoSetDict

# extrude Film
runApplication -s film myExtrudeToRegionMesh -dict system/extrudeToRegionMeshDictFilm -overwrite

# extrude pyrolysis
runApplication -s pyr myExtrudeToRegionMesh -dict system/extrudeToRegionMeshDictPyr -overwrite

# change samplePatch in the boundary to coupled patch betwee region0 and
# pyrolysis
foamDictionary constant/filmRegion/polyMesh/boundary \
               -entry entry0.region0_to_filmRegion_coupledWall.samplePatch \
               -set region0_to_pyrolysisRegion_coupledWall

# create faceSets for inlet, outlet, sides for the Film
runApplication topoSet -region filmRegion
mv log.topoSet log.topoSet.film

# create actual patches
runApplication createPatch -region filmRegion -overwrite
mv log.createPatch log.createPatch.film

sed -i '/uniform/d' constant/polyMesh/boundary
sed -i '/uniform/d' constant/pyrolysisRegion/polyMesh/boundary
sed -i '/uniform/d' constant/filmRegion/polyMesh/boundary

cp -rf 0_backup 0

nProcs=$(getNumberOfProcessors)


if [ "$nProcs" -gt "1" ];
then
    runApplication decomposePar -allRegions
fi

mv log.* runFiles

#------------------------------------------------------------------------------
