#!/bin/bash

#Adapted from tutorial located at: http://www.holzmann-cfd.de/index.php/en/
# $1 change from DAKOTA to OF file
# $2 pipe OF output to DAKOTA

# Update OF through DAKOTA
# ------------------------------------------------------------------------------
dprepro $1 system/dakotaParameters.orig system/dakotaParameters

# Run simulation with new parameter set
# ------------------------------------------------------------------------------

    # Get parameters and remove possible scientific notation
    #---------------------------------------------------------------------------
    filmFlowRate=`head -5 system/dakotaParameters | tail -1 | cut -d'=' -f2`
    filmFlowRate=`echo $filmFlowRate | sed -e 's/[eE]+*/\*10\^/'`

    #filmTemperature=`head -6 system/dakotaParameters | tail -1 | cut -d'=' -f2`
    #filmTemperature=`echo $filmTemperature | sed -e 's/[eE]+*/\*10\^/'`

    # Rescale parameters to real values
    #---------------------------------------------------------------------------
    #filmFlowRateScaled=`echo "tmp=$filmFlowRate*(1900-70) + 70; scale=2; tmp/1" | bc -l` #70 to 1900 ml/min
    #filmFlowRateScaledForFoam=`echo "$filmFlowRateScaled/(1000*1000*60)" | bc -l` #convert to liters/s

    #filmFlowRateScaled=`echo "tmp=$filmFlowRate*0.02; scale=6; tmp/1" | bc -l` #0 to 0.02 m/s
     filmFlowRateScaled=`echo "$filmFlowRate*0.02 + 0.0" | bc -l` #0 to 0.02 m/s

    # Print current loop number and parameter values
    #---------------------------------------------------------------------------
    funcIter=`cat .funcIter`

    >&2 echo -e ""
    >&2 echo -e "Function Iteration : $funcIter"
    >&2 echo "Film inflow velocity : $filmFlowRateScaled"
    >&2 echo -e ""

    # Set new parameter values
    #---------------------------------------------------------------------------
    sed -i "52s/.*/        value           uniform (0 -$filmFlowRateScaled 0);/" 0/filmRegion/Uf

    # Run OpenFOAM
    #---------------------------------------------------------------------------
    fireDyMFoam > log.fireDyMFoam 2>&1

    # Get desired quantitites and update cost function
    #---------------------------------------------------------------------------
    #postProcess -func integrateHRR -time '5:6' > log.integrateHRR
    #grep "volIntegrate() of Qdot " log.integrateHRR | awk '{print $5}' > intHRR.txt
    #meanIntHRR=`awk '{ total += $1; count++ } END { print total/count }' intHRR.txt`
    #func=`echo 0.9*$meanIntHRR/99980.3 + 0.1*$filmFlowRateScaled/1000 | bc -l`

    solidMassLoss=`grep "Total gas mass produced " log.fireDyMFoam | tail -1 | awk '{print $7}'`
    solidMassLoss=`echo $solidMassLoss | sed -e 's/[eE]+*/\*10\^/'`
    func=`echo "0.5*$solidMassLoss/0.0090755313833 + 0.5*$filmFlowRateScaled/0.01" | bc -l`

    echo $func > .dakotaInput.dak

    >&2 echo -e ""
    #>&2 echo "Mean Integrated HRR : $meanIntHRR"
    >&2 echo "Solid mass loss : $solidMassLoss"
    >&2 echo "Cost Function : $func"
    >&2 echo -e ""

    # Clean Case
    #---------------------------------------------------------------------------
    mkdir runFiles/Optimization$funcIter
    cp -rf log.fireDyMFoam runFiles/Optimization$funcIter

    foamListTimes -rm
    rm -rf postProcessing

    # Increase the loop number and store in dummy file
    #--------------------------------------------------------------------------
    echo $((funcIter+1)) > .funcIter

# Pipe output file to DAKOTA
#------------------------------------------------------------------------------
cp .dakotaInput.dak $2

sleep 1

#------------------------------------------------------------------------------
