#!/bin/sh

cp -rf 0_backup 0

echo "building mesh"
blockMesh > log.blockMesh
snappyHexMesh -overwrite > log.snappyHexMesh

decomposePar > log.decomposePar
renumberMesh -overwrite > log.renumberMesh

mkdir runFiles
mv log* runFiles

echo "running solver"
mpirun -np 3 diffusionFireFoam -parallel > log.diffusionFireFoam 2>&1

postProcess -func sample
#------------------------------------------------------------------------------
