#!/bin/sh

cp -rf 0_backup 0

echo "building mesh"
blockMesh > log.blockMesh
snappyHexMesh -overwrite > log.snappyHexMesh

#topoSet -dict system/topoSetDict1 > log.topoSet1
#createPatch -dict system/createPatchDict -overwrite > log.createPatch

renumberMesh -overwrite > log.renumberMesh
decomposePar > log.decomposePar

mkdir runFiles
mv log* runFiles

echo "running solver"
mpirun -np 4 diffusionFireFoam -parallel > log.diffusionFireFoam 2>&1

#------------------------------------------------------------------------------
