#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#src
cd src
wmake libso dynamicMesh
wmake libso dynamicFvMesh
wmake libso radiationModels
wmake libso combustionModels
wmake thermophysicalModels/solidChemistryModel
wmake libso TurbulenceModels/compressible
wmake libso regionModels/regionModel
wmake libso regionModels/pyrolysisModels
wmake libso regionModels/surfaceFilmModels
wmake libso regionModels/regionCoupling
wmake libso lagrangian/intermediate
wmake libso lagrangian/turbulence
wmake libso finiteVolume/fields/fvPatchFields/custom
cd ..

#solvers
cd applications/solvers/combustion
wmake diffusionFireFoam
wmake diffusionFireFoam/rhoDiffusionFireFoam
wmake wildFireFoam
wmake wildFireFoam/rhoWildFireFoam
cd ../../..

