#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#src
cd src
wclean dynamicMesh
wclean dynamicFvMesh
wclean radiationModels
wclean combustionModels
wclean TurbulenceModels/compressible
wclean regionModels/regionModel
wclean regionModels/pyrolysisModels
wclean regionModels/surfaceFilmModels
wclean regionModels/regionCoupling
wclean lagrangian/intermediate
wclean lagrangian/turbulence
wclean finiteVolume/fields/fvPatchFields/custom
cd ..

#solvers
cd applications/solvers/combustion
wclean diffusionFireFoam
wclean diffusionFireFoam/rhoDiffusionFireFoam
wclean wildFireFoam
wclean wildFireFoam/rhoWildFireFoam
cd ../../../

