#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#src
cd src
wmake libso dynamicFvMesh
wmake libso combustionModels
wmake libso thermophysicalModels/radiationModels
wmake libso  finiteVolume/fields/fvPatchFields/custom/
cd ..

#solvers
cd applications/solvers/combustion
wmake diffusionFireFoam
cd ../../..
