#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#sed -i '19s/.*/    \/\/"libcustomFvPatchFields.so"/' system/controlDict

cp -rf 0_backup 0

runApplication blockMesh

runApplication -s 1 snappyHexMesh -overwrite -dict system/snappyHexMeshDict1

runApplication -s 2 snappyHexMesh -overwrite -dict system/snappyHexMeshDict2

runApplication -s f \
    topoSet -dict system/f.topoSetDict

# create the pyrolysis region.
runApplication myExtrudeToRegionMesh -overwrite

sed -i '/uniform/d' constant/polyMesh/boundary
sed -i '/uniform/d' constant/panelRegion/polyMesh/boundary

cp 0/ph_rgh.orig 0/ph_rgh

nProcs=$(getNumberOfProcessors)

if [ "$nProcs" -gt "1" ];
then
    runApplication decomposePar -allRegions
fi

mkdir runFiles
mv log* runFiles

#sed -i '19s/.*/    "libcustomFvPatchFields.so"/' system/controlDict


#------------------------------------------------------------------------------
