#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=fireDyMFoam

./Allmesh

nProcs=$(getNumberOfProcessors)

if [ "$nProcs" -gt "1" ];
then
    echo "Running $application in parallel on $nProcs processors"
    ( mpirun -np $nProcs $application -parallel > log.$application 2>&1 )
else
    echo "Running $application in serial"
    ( $application > log.$application 2>&1 )
fi

#paraFoam -touch
#paraFoam -touch -region panelRegion


#------------------------------------------------------------------------------
