#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=wildFireFoam
nProcs=$(getNumberOfProcessors)

cp -rf 0_backup 0

echo "Creating Mesh"

runApplication blockMesh

runApplication surfaceFeatures

runApplication snappyHexMesh -overwrite

runApplication topoSet -dict system/topoSetDict.pyrolysis

runApplication extrudeToRegionMesh -overwrite

runApplication mapFields -sourceTime '20' ../DyMspinup

runApplication setFields -region pyrolysisRegion

mkdir runFiles

mv log* runFiles

#runApplication setFields

mv log* runFiles

#runApplication wildFireFoam

if [ "$nProcs" -gt "1" ];
then
    echo "Running $application in parallel on $nProcs processors"
    ( mpirun -np $nProcs $application -parallel > log.$application 2>&1 )
else
    echo "Running $application in serial"
    ( $application > log.$application 2>&1 )
fi

#------------------------------------------------------------------------------
